version: '3'

services:
  quickstart:
    build:
      context: .
    environment:
      PGUSER: message_store
      PGPASSWORD: message_store
      PGDATABASE: message_store
      PGPORT: 5432
      PGHOST: db
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:11.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/11/data
    restart: always
    volumes:
      - pgdata11:/var/lib/postgresql/11/data
volumes:
  pgdata11:
